name: Deploy Next.js to Firebase

on:
  push:
    branches:
      - main  # Trigger deploys on pushes to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci  # ensures package-lock.json is used

      # 4️⃣ Build Next.js
      - name: Build Next.js
        run: npm run build

      # 5️⃣ Deploy to Firebase Hosting using CI token
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --token $FIREBASE_TOKEN
